### PR TITLE
Discussion PR for conda envs split

### PR DESCRIPTION
**Pull request by bryevdv**
cc @manopapad @magnatelee @marcinz @m3vaz 

@manopapad asked if I might make a first stab at splitting out the env files as I described earlier. This PR splits out the current single conda env dev file into per-python version files:

```
environment-test-3.8.yml
environment-test-3.9.yml
environment-test-3.10.yml
```

These are  "kitchen sink" env files, that should usable for any dev who wants to install, run tests, and build docs locally. I think these are immediately useful to devs in order to create per-python dev environments easily. 

I think the commented groupings in these files represent the usage of the various dependencies, but please provide any feedback. 

So then the question is what further refinements or splits might be useful for CI? Some ideas:

* an `environment-build.yml` This would be much more minimal, with `conda-build` (and `ripgrep`) just enough to create the conda package consumed by later build stages

* If there is a single job responsible for building docs, then a more minimal `environment-docs.yml` could be created without the build/testing deps

* Could also truly split all these into `environment-dev-3.x.yml` (kitchen sink, used by devs locally) and `environment-test-3.x.yml` (used in CI test runs, omits docs and build deps). These envs are pretty small to be honest, so personally I think that might be overkill (i.e. just use these for CI and local dev to have fewer env files to maintain)

### Notes

* Moved docs/examples deps to `pip`. In my experience sphinx extensions, etc can have the most conda availability issues and I think it might make the install a but quicker as well. But could potentially be reverted to conda if desired.
* I have verified all these files are installable via e.g.
    ```
    conda env create -n dev310 -f environment-test-3.10.yml
    ```

### Questions

* Assuming these are refined for use in `cunumeric` what (strict?) subset should be used for `legate.core`? Or, just keep the two repos in sync with each other?
* What automation/checks are reasonable to help keep env files consistent when updates are made?

### CODE REVIEW

**Comment by bryevdv** [comment]
Just noting that these do work really well for getting a dev env for a specific Python version up and running, at least with the current setup/install system. Starting from zero:
```sh
$ conda env create -n dev310 -f environment-test-3.10.yml

$ conda activate dev38; export PATH=~/work/legate.core/install38/bin:$PATH

# legate.core
$ ./install.py --install-dir=install38 --cuda  --arch turing

# cunumeric
$ python setup.py --with-core ~/work/legate.core/install38 --with-cutensor ~/anaconda3/envs/dev38

# run tests
$ ./test.py --use=cuda
```

presumably @trxcllnt cmake work will make the last two even simpler, but I am not sure about conda env management for local dev with cmake. @trxcllnt does the cmake work also handle conda env creation, or does it assume they are already created up front?

**Comment by trxcllnt** [comment]
@bryevdv CMake does not create a conda env, but it will use libraries installed in the conda env if instructed to do so.

**Comment by bryevdv** [comment]
Incidentally I opened an issue on conda regarding templatized env files but who knows when/if that will go anywhere (https://github.com/conda/conda/issues/11465)

**Comment by manopapad** [comment]
Sorry for being late to the party.

> what further refinements or splits might be useful for CI?

I think just sticking with kitchen-sink is fine for now.

> Moved docs/examples deps to pip

Are these not found under conda? I don't know if this is common practice, but my gut reaction is that if these are available under conda we needn't introduce another layer.

> Assuming these are refined for use in cunumeric what (strict?) subset should be used for legate.core? Or, just keep the two repos in sync with each other?
> What automation/checks are reasonable to help keep env files consistent when updates are made?

I don't really have great answers for these. It might not even be worth it to maintain separate conda env files for just legate.core at this stage, given that legate.core doesn't do much by itself.

Otherwise these look good!

**Comment by magnatelee** [comment]
> @manopapad @magnatelee would these be useful to merge as a start? I do think they are useful for dev setup at least (and seems that will continue to be the case with @trxcllnt's work)

Yes, let's merge these. I'd accompany these with some custom template so we don't accidentally miss out a file for every new dependency, but three separate files seem manageable at least for now.

**Comment by bryevdv** [comment]
> Are these not found under conda? 

Maybe presently. But my experience over the last several years is that sphinx extensions in particular can spotty with conda. I'd like to avoid a situation where we use conda for everything now and then want to add `sphinx-opengraph` (or whatever) later and it's not in conda. Doing half-in/half-out with sphinx extensions has also 100% caused problems I've had to spend time fixing, so we'd just have to switch everything to pip at that point. I'd rather just be pro-active and let pip handle this one little corner since I have seen this kind of setup work without issue for several years now. 

> I don't really have great answers for these. It might not even be worth it to maintain separate conda env files for just legate.core at this stage, given that legate.core doesn't do much by itself.

To be clear, my own opinion is that we should just mirror the files in both repos, even if that makes the ones for legate have a couple of "unnecessary" dependencies. These envs are small, and I think that is just simpler to maintain. But if we did want to pare down. the examples and docs sections could be jettisoned, at least.

**Comment by bryevdv** [comment]
> Are these not found under conda? 

Maybe presently. But my experience over the last several years is that sphinx extensions in particular can spotty with conda. I'd like to avoid a situation where we use conda for everything now and then want to add `sphinx-opengraph` (or whatever) later and it's not in conda. Doing half-in/half-out with sphinx extensions has also 100% caused problems I've had to spend time fixing, so we'd just have to switch everything to pip at that point. I'd rather just be pro-active and let pip handle this one little corner since I have seen this kind of setup work without issue for several years now. 

> I don't really have great answers for these. It might not even be worth it to maintain separate conda env files for just legate.core at this stage, given that legate.core doesn't do much by itself.

To be clear, my own opinion is that we should just mirror the files in both repos, even if that makes the ones for legate have a couple of "unnecessary" dependencies. These envs are small, and I think that is just simpler to maintain. But if we did want to pare down. the examples and docs sections could be jettisoned, at least.

**Comment by magnatelee** [comment]
> To be clear, my own opinion is that we should just mirror the files in both repos, even if that makes the ones for legate have a couple of "unnecessary" dependencies. These envs are small, and I think that is just simpler to maintain. But if we did want to pare down for the legate repo, then the examples and docs sections could be jettisoned, at least.

I think mirroring is fine for now, but keep in mind that
 Legate Pandas would pull in quite a few transitive dependencies that are otherwise unnecessary if you only want to use cuNumeric.

**Pull request merged**
