### PR TITLE
Refactor test driver for cpu/gpu sharding

### PR DESCRIPTION
**Pull request by bryevdv**
This PR add support for cpu/gpu sharding so that that it is no longer necessary to unset `REALM_SYNTHETIC_CORE_MAP`

Other notes:

* Test stages were refactored and simplified. Most control was moved to base protocol class, with stage implementations responsible only for computing the sharding spec, etc. 
* `--debug` now also includes explicitly modified env vars in printed output
* `--fbmem` command line option was added for GPU stage
* Some missing docs were added
* Some minimal tests of sharding computations were added, but perhaps more is advised

Tested locally with MPI GASNet conduit, with variations of the following invocations:
```
GASNET_QUIET=1 ./test.py --use=openmp --omps=2 --ompthreads=1 --launcher=mpirun --debug
GASNET_QUIET=1 ./test.py --use=cpus --cpus 2 --launcher=mpirun --debug 
GASNET_QUIET=1 ./test.py --use=cuda --gpus 2 --launcher=mpirun --debug
GASNET_QUIET=1 ./test.py --use=eager --launcher=mpirun --debug
```

### CODE REVIEW

**Comment by bryevdv** [comment]
rebuilding with latest branch merged and without gasnet to see if I can repro locally

**Comment by magnatelee** [comment]
@bryevdv I have no idea, and I can't reproduce it locally. the only difference is that you're using the mpi conduit, which isn't the most reliable conduit. can you run without gasnet and see if you can reproduce it? also, I'd want a full output from the crash. that should have a runtime stacktrace.

**Comment by magnatelee** [comment]
@bryevdv also note that I'm seeing a different issue when I tried your command:
```
Traceback (most recent call last):
  File "/home/nfs/wonchanl/anaconda3/envs/legate-new-pyarrow/lib/python3.10/threading.py", line 1538, in _shutdown
    assert tlock.locked()
```
this looks like a variant of the issue with `threading` that I though I fixed several months ago. though I think I should put in a more robust fix, please try to bind more than one logical cores to a legate process as a workaround.

**Comment by bryevdv** [comment]
OK after merging an rebuilding w/o gasnet I do see the error locally. @magnatelee  here is the full output
```
gas38 ❯ LEGATE_TEST=1 legate tests/integration/test_arg_reduce.py -cunumeric:test --cpus 2 --cpu-bind 0,1 -v --sysmem=1024 
[0 - 7f386a769000]    0.000097 {4}{threads}: reservation ('Python-1 proc 1d00000000000004') cannot be satisfied
===================================================================================================================================== test session starts ======================================================================================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0 -- /home/bryan/anaconda3/envs/gas38/bin/python3
cachedir: .pytest_cache
rootdir: /home/bryan/work/cunumeric, configfile: pyproject.toml
plugins: mock-3.8.2, cov-3.0.0
collected 10 items                                                                                                                                                                                                                                                                             

tests/integration/test_arg_reduce.py::test_argmax_and_argmin[True-0] PASSED                                                                                                                                                                                                              [ 10%]
tests/integration/test_arg_reduce.py::test_argmax_and_argmin[True-1] PASSED                                                                                                                                                                                                              [ 20%]
tests/integration/test_arg_reduce.py::test_argmax_and_argmin[True-2] legion_python: /home/bryan/work/legate.core/install38/include/legion/legion_domain.inl:999: Legion::Domain::operator Legion::Rect<DIM, T>() const [with int DIM = 1; T = long long int; Legion::Rect<DIM, T> = Realm::Rect<1, long long int>]: Assertion `DIM == dim' failed.
Fatal Python error: Aborted

Thread 0x00007f38619ac000 (most recent call first):
  File "/home/bryan/work/legate.core/install38/lib/python3.8/site-packages/legate/core/_legion/future.py", line 157 in get_buffer
  File "/home/bryan/work/cunumeric/cunumeric/deferred.py", line 310 in get_scalar_array
  File "/home/bryan/work/cunumeric/cunumeric/deferred.py", line 224 in __numpy_array__
  File "/home/bryan/work/cunumeric/cunumeric/array.py", line 664 in __array__
  File "/home/bryan/work/cunumeric/cunumeric/coverage.py", line 106 in wrapper
  File "/home/bryan/work/cunumeric/cunumeric/array.py", line 680 in __bool__
  File "/home/bryan/work/cunumeric/cunumeric/coverage.py", line 106 in wrapper
  File "/home/bryan/work/cunumeric/tests/integration/test_arg_reduce.py", line 34 in test_argmax_and_argmin
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/python.py", line 1761 in runtest
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/runner.py", line 338 in from_call
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/runner.py", line 258 in call_runtest_hook
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/main.py", line 322 in _main
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/bryan/anaconda3/envs/gas38/lib/python3.8/site-packages/_pytest/config/__init__.py", line 164 in main
  File "tests/integration/test_arg_reduce.py", line 48 in <module>
  File "/home/bryan/work/legate.core/install38/lib/python3.8/site-packages/legion_top.py", line 255 in run_path
  File "/home/bryan/work/legate.core/install38/lib/python3.8/site-packages/legion_top.py", line 440 in legion_python_main
Signal 6 received by node 0, process 2289623 (thread 7f38619ba000) - obtaining backtrace
Signal 6 received by process 2289623 (thread 7f38619ba000) at: stack trace: 18 frames
  [0] = /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f386c055090]
  [1] = /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f386c05500b]
  [2] = /lib/x86_64-linux-gnu/libc.so.6(+0x43090) [0x7f386c055090]
  [3] = /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb) [0x7f386c05500b]
  [4] = /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b) [0x7f386c034859]
  [5] = /lib/x86_64-linux-gnu/libc.so.6(+0x22729) [0x7f386c034729]
  [6] = /lib/x86_64-linux-gnu/libc.so.6(+0x33fd6) [0x7f386c045fd6]
  [7] = /home/bryan/work/legate.core/install38/lib/libcunumeric.so(+0x2bc9a5) [0x7f37c59c59a5]
  [8] = /home/bryan/work/legate.core/install38/lib/libcunumeric.so(Legion::ReductionAccessor<cunumeric::ArgmaxReduction<double>, true, 1, long long, Realm::AffineAccessor<cunumeric::ArgmaxReduction<double>::RHS, 1, long long>, false> legate::Store::reduce_accessor<cunumeric::ArgmaxReduction<double>, true, 1>() const+0x98) [0x7f37c5c91bf8]
  [9] = /home/bryan/work/legate.core/install38/lib/libcunumeric.so(+0x53fab2) [0x7f37c5c48ab2]
  [10] = /home/bryan/work/legate.core/install38/lib/libcunumeric.so(+0x552830) [0x7f37c5c5b830]
  [11] = /home/bryan/work/legate.core/install38/lib/libcunumeric.so(legate::ReturnValues legate::LegateTask<cunumeric::ScalarUnaryRedTask>::legate_task_wrapper<&cunumeric::ScalarUnaryRedTask::cpu_variant>(Legion::Task const*, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, Legion::Internal::TaskContext*, Legion::Runtime*)+0xb8) [0x7f37c5c94638]
  [12] = /home/bryan/work/legate.core/install38/lib/libcunumeric.so(void Legion::LegionTaskWrapper::legion_task_wrapper<legate::ReturnValues, &(legate::ReturnValues legate::LegateTask<cunumeric::ScalarUnaryRedTask>::legate_task_wrapper<&cunumeric::ScalarUnaryRedTask::cpu_variant>(Legion::Task const*, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, Legion::Internal::TaskContext*, Legion::Runtime*))>(void const*, unsigned long, void const*, unsigned long, Realm::Processor)+0x48) [0x7f37c5c948f8]
  [13] = /home/bryan/work/legate.core/install38/lib/librealm.so(+0x2c1552) [0x7f386c6b1552]
  [14] = /home/bryan/work/legate.core/install38/lib/librealm.so(+0x2c15c6) [0x7f386c6b15c6]
  [15] = /home/bryan/work/legate.core/install38/lib/librealm.so(+0x2c2060) [0x7f386c6b2060]
  [16] = /home/bryan/work/legate.core/install38/lib/librealm.so(+0x2a20fb) [0x7f386c6920fb]
  [17] = /lib/x86_64-linux-gnu/libc.so.6(+0x5b4e0) [0x7f386c06d4e0]
legion_python: /home/bryan/work/legate.core/install38/include/legion/legion_domain.inl:999: Legion::Domain::operator Legion::Rect<DIM, T>() const [with int DIM = 1; T = long long int; Legion::Rect<DIM, T> = Realm::Rect<1, long long int>]: Assertion `DIM == dim' failed.
/home/bryan/work/legate.core/install38/bin/bind.sh: line 107: 2289623 Aborted                 numactl "$@"
```

**Comment by bryevdv** [comment]
@magnatelee the only way I don't get this error is if I leave off `LEGATE_TEST=1` and leave off `-cunumeric:test`
`

**Comment by bryevdv** [comment]
merged in latest default branch for good measure since it's been awhile

**Comment by bryevdv** [comment]
@magnatelee any thoughts on this PR? I think it would be good to merge near the beginning of a new release cycle. That said, a quick comparison with other recent PRs seems to indicate that the tests run more slowly on this PR. This PR explicitly reserves utility cores, where the old test runner does not. My offhand speculation is that might explain, especially if the CI runners do not have many cores (I'm not actually sure what their specs are).

**Comment by bryevdv** [comment]
Ah, no I forgot, we are running with the verbose flag, which pins to one worker. I think that the new runner would do better on the CI machines if that restriction is lifted.

**Comment by bryevdv** [comment]
Just by way of quick comparison, I ran
```
./test.py --use=cpus,cuda,openmp,eager --unit --omps=2 --ompthreads=1 --cpus
```
on my local system two ways:

#### old runner, verbose mode (1 worker) 
```
1631.75s user 421.01s system 217% cpu 15:42.30 total
```

#### new runner, non-verbose (multiple workers)
```
527.69s user 205.07s system 378% cpu 7:37.43 total
```

**Review by magnatelee — APPROVED** [review]

**Comment by magnatelee** [comment]
>  I do suspect that some of that comes down to the extra reserved utility cores.

yeah, the old script might enjoy a higher degree of parallelism as it doesn't take into account the number of utility processors. I guess we could do that, which would turn off the pinning and might be better.

**Comment by magnatelee** [comment]
I think we can merge this PR as it is and make follow-on PRs to improve it. One improvement we can potentially make is to have each shard run all the tests within one Legate process, instead of running separate commands for them. I believe there's some tool for doing this.

**Comment by bryevdv** [comment]
>  I think we can merge this PR as it is and make follow-on PRs to improve it. One improvement we can potentially make is to have each shard run all the tests within one Legate process, instead of running separate commands for them. I believe there's some tool for doing this.

Possibly, though I think there is an implicit assumption that the test jobs are roughly "equal" in doing that. Currently the test running runs jobs until all the shards are filled. Then, when a job finishes, its shard (whatever it happens to be) is given to the next job. Pre-assigning all the tests to shards would risk e.g. putting 10 super fast tests on one shard and 10 super-slow tests on another.

In any case, my next plan was to work on output collating, so that we can simply stop capping to a single worker in CI (either by using a different mode than verbose, or making verbose no longer cap workers)

**Pull request merged**
