### PR TITLE
removing unused variable in diagonal implementation

### PR DESCRIPTION
**Pull request by ipdemes**

### CODE REVIEW

**Review by manopapad — APPROVED** [review]
Note that you'll need to update some tests in `test_advanced_indexing.py`

**Comment by ipdemes** [comment]
@manopapad : do you mean `test_indexing_routines.py`? I don't think we were passing `axes` in any of the tests

**Comment by ipdemes** [comment]
@manopapad : NVM, I realized that test_index_routines.py was failing. Pushed the fix.

**Review by manopapad — APPROVED** [review]

**Comment by m3vaz** [comment]
pre-commit.ci run

**Pull request merged**
