### PR TITLE
Illustrate kernel and dispatch refactor

### PR DESCRIPTION
**Pull request by jjwilke**
This illustrates the design proposed in https://docs.google.com/document/d/13Lp7Ann8FaagYTHGLL-SvLa3Rc9K30TrOkiyYqxZ2bA

### CODE REVIEW

**Comment by magnatelee** [comment]
looks like there are some changes in the core that this PR relies on: https://github.com/nv-legate/cunumeric/runs/7584237922?check_suite_focus=true#step:9:12579 in case you want to line up PRs in legate core and cunumeric, you need to put a `_pr` suffix to their branch names.

**Comment by marcinz** [comment]
@jjwilke What is the status of this PR?

**Comment by magnatelee** [comment]
@jjwilke I assume this is subsumed by #573, right? if so, please close this PR.

**Comment by jjwilke** [comment]
This has some extra stuff relative to #573 meant to simplify dispatch, double dispatch, etc, using constexpr. We can close it. It's just a draft to illustrate a technique.

**Pull request closed without merging**
