### PR TITLE
Bump up NumPy version

### PR DESCRIPTION
**Pull request by magnatelee**
This PR bumps up the minimum NumPy version to 1.22 and removes code that becomes obsolete due to that change.

### CODE REVIEW

**Comment by bryevdv** [comment]
FYI @magnatelee it seems Numpy 1.22 not installable for Python 3.7
```
legate37 ❯ conda create -c conda-forge -c defaults -n foo python=3.7 "numpy>=1.22"
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                      

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.7
numpy[version='>=1.22'] -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
numpy[version='>=1.22'] -> python_abi=3.8[build=*_cp38] -> python[version='3.10.*|3.8.*|3.9.*']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

```

**Comment by manopapad** [comment]
IIRC it is safe to remove those fallbacks starting with NumPy 1.20 (which supports python 3.7).

**Comment by bryevdv** [comment]
Also xref: https://github.com/nv-legate/legate.core/pull/206

**Comment by magnatelee** [comment]
> IIRC it is safe to remove those fallbacks starting with NumPy 1.20 (which supports python 3.7).

You're right, but 1.22 is required for better typing support too.

**Pull request merged**
