### PR TITLE
Add Cmake flag to ensure we're propagating thread_count

### PR DESCRIPTION
**Pull request by reazulhoque**
Thread count is not being propagated to Cmake. This fixes that.

### CODE REVIEW

**Comment by magnatelee** [comment]
also I don't recall we had any issue with the parallel build... can you describe what you're trying to fix with this PR?

**Comment by reazulhoque** [comment]
@magnatelee We are propagating to cmake what users have provided with `-j` flag to `install.py`.

Without this fix user provided option will not be respected by cmake.

**Comment by manopapad** [comment]
To be clear, install.py does pass -j directly to ninja/make, which is the last stage of the build, and covers all C++ compilation. We would have to pass this to cmake if we were using cmake --build rather than ninja/make directly. The problem is that compilation of the rust profiler expects to read -j from cmake.

**Review by manopapad — APPROVED** [review]
If you can, please also open a corresponding PR on https://github.com/nv-legate/legate.core.

**Pull request merged**
