### PR TITLE
Update to the latest Legion

### PR DESCRIPTION
**Pull request by marcinz**
For testing, this PR points to the PR version of legate.core. Before merge, the version of legate.core should be changed to the commit on the legate.core dev branch.

### CODE REVIEW

**Comment by marcinz** [comment]
@manopapad Tests seem to be failing with the latest Legion.

**Comment by lightsighter** [comment]
Have you tried turning off the caching allocator?
https://github.com/StanfordLegion/legion/issues/1513#issuecomment-1649736543

**Comment by manopapad** [comment]
> Have you tried turning off the caching allocator?

That didn't fix it

**Comment by manopapad** [comment]
`git bisect` identified this control_replication commit as the culprit:

```
commit 6e31c84148103ace33b7812f267bc92f33b7aada
Merge: ea62f9acf 73fbb52c5
Author: Steven Gurfinkel <sgurfinkel@nvidia.com>
Date:   Fri Jul 21 14:56:44 2023 +0000

    Merge branch 'sgurfinkel/reduce_future' into 'control_replication'

    [Legion] add initial value parameter to reduce_future_map()

    See merge request StanfordLegion/legion!846
```

**Comment by lightsighter** [comment]
Here is a backtrace for some invalid reads that are occuring:

```
==3189703== Invalid read of size 8
==3189703==    at 0x4848B5F: memmove (vg_replace_strmem.c:1398)
==3189703==  Address 0xf23d0a8 is 7 bytes after a block of size 1 alloc'd
==3189703==    at 0x483D635: malloc (vg_replace_malloc.c:392)
==3189703==    by 0x18A3D4479: legate::pack_returned_exception(legate::ReturnedException const&, void*&, unsigned long&) (return.cc:104)
==3189703==    by 0x18A3D44CB: legate::returned_exception_init(Realm::ReductionOpUntyped const*, void*&, unsigned long&) (return.cc:113)
==3189703==    by 0x6B6F67C: Legion::Internal::AllReduceOp::initialize(Legion::Internal::InnerContext*, Legion::FutureMap const&, int, bool, unsigned int, unsigned long, Legion::Internal::Provenance*, Legion::Future) (legion_ops.cc:23169)
==3189703==    by 0x69B9DE2: Legion::Internal::InnerContext::reduce_future_map(Legion::FutureMap const&, int, bool, unsigned int, unsigned long, Legion::Internal::Provenance*, Legion::Future) (legion_context.cc:6473)
==3189703==    by 0x6ACAB44: Legion::Runtime::reduce_future_map(Legion::Internal::TaskContext*, Legion::FutureMap const&, int, bool, unsigned int, unsigned long, char const*, Legion::Future) (legion.cc:6341)
==3189703==    by 0x690E681: legion_future_map_reduce_with_initial_value (legion_c.cc:3333)
==3189703==    by 0x690E558: legion_future_map_reduce (legion_c.cc:3312)
==3189703==    by 0x21FEFA49: ffi_call_unix64 (in /home/mebauer/miniconda3/envs/legate/lib/libffi.so.8.1.0)
==3189703==    by 0x21FEEFE9: ffi_call_int (in /home/mebauer/miniconda3/envs/legate/lib/libffi.so.8.1.0)
==3189703==    by 0x2877C493: cdata_call (in /home/mebauer/miniconda3/envs/legate/lib/python3.11/site-packages/_cffi_backend.cpython-311-x86_64-linux-gnu.so)
==3189703==    by 0x1762E5AA3: _PyObject_MakeTpCall (call.c:214)
```

I can't explain why they are happening though since I don't know how to pass `--db-attach=yes` to valgrind through the legate launcher at the moment. 

@sgurfinkel for visibility.

**Comment by marcinz** [comment]
I updated to the latest Legion, and fewer tests seem to fail.

**Comment by lightsighter** [comment]
> I updated to the latest Legion, and fewer tests seem to fail.

But there are still failing tests right? I think that the fundamental problem is still there (whatever it is).

**Comment by manopapad** [comment]
I'm going to take this opportunity to test a change to the test configuration, whereby we tell pytest to not install python's signal handler, which tends to shadow Realm's printing of C++ backtraces. Hopefully this results in more informative backtraces when the C++ side crashes.

**Comment by manopapad** [comment]
@marcinz it looks like tests passed, so I think we can merge this and https://github.com/nv-legate/legate.core/pull/803

**Pull request merged**
