### PR TITLE
Add missing includes to aid intellisense providers

### PR DESCRIPTION
**Pull request by trxcllnt**
Add `#include` directives to `.inl` headers to aid intellisense providers (like `clangd`) who infer the compile commands from the C++ build commands.

Previously, `arg.h` included `arg.inl` at the bottom, but this PR combines them into one file.

1. The relationship between `arg.h` and `arg.inl` deviates from all other usages of `.h`/`.inl` pairs where both files are explicitly included by a single compilation unit.
2. In order to provide intellisense results for the symbols in `arg.inl`, clang would need to see an include for `arg.h` at the top of the file (leading to an illegal circular dependency).
  An alternative solution would be to remove `#include "arg.inl"` from the end of `arg.h` and either...
    * change all `#include "arg.h"` to be `#include "arg.inl"`
    * add `#include "arg.inl"` after each instance of `#include "arg.h"`

Both of those seem less maintainable and more confusing than just combining the files into one header.

I also added `#pragma once` to the `.inl` files. Not sure if this is strictly necessary, but it seemed like a safe addition.

Related to:
* https://gitlab.com/StanfordLegion/legion/-/merge_requests/498
* https://github.com/nv-legate/legate.core/pull/249

### CODE REVIEW

**Review by manopapad — APPROVED** [review]
I agree with your solution for arg.h, but I'll let @magnatelee have the final say, since he wrote that code.

**Comment by trxcllnt** [comment]
Another thing I noticed is many of the headers are C++, but still end in `.h`. Editors will syntax-highlight `.h` files as C instead of C++, and this makes it harder for devs to distinguish which headers need to only contain C (e.g. for inclusion by Python).

The canonical approach I've seen is to name C++ headers with `.hpp` extensions (and any CUDA C++ headers with `.cuh` extensions). If others agree, I can make that change in this PR as well.

**Comment by manopapad** [comment]
> The canonical approach I've seen is to name C++ headers with .hpp extensions (and any CUDA C++ headers with .cuh extensions). If others agree, I can make that change in this PR as well.

I am fine with this, but Legate is just following the convention used in Legion, so @lightsighter should comment.

Note that this rule would need to be copied for .hpp: https://github.com/nv-legate/legate.core/blob/branch-22.07/src/legate.mk#L214

**Comment by manopapad** [comment]
> If others agree, I can make that change in this PR as well.

If we move ahead with this, I would rather we do it in a separate PR.

**Comment by magnatelee** [comment]
I actually don't like the way arg.h and arg.inl are merged. A separate .inl file for definitions is the idiom we've been using for a while for better human readability. (See other uses of the pattern here: https://github.com/nv-legate/legate.core/tree/branch-22.07/src/core/data, and you can find more in the Legion repository) Merging the files would help IDEs but please note that not everyone is using an IDE. I'd be actually okay with including both .h and .inl if necessary; in my opinion doing so would be better for code maintenance than smashing the files into one.

**Comment by magnatelee** [comment]
> Another thing I noticed is many of the headers are C++, but have .h extensions. Editors will syntax-highlight .h files as C instead of C++, and this makes it harder for devs to distinguish which headers need to only contain C (e.g. for inclusion by Python).

I'm fine with renaming the files, as long as you categorize them correctly. I believe all headers are C++ headers except they are using the old-style define-once idiom using C macros.

I agree with @manopapad that the changes should be in a separate PR.

**Comment by trxcllnt** [comment]
> I'd be actually okay with including both .h and .inl if necessary

Sure, I can do that.

**Comment by trxcllnt** [comment]
@magnatelee I pushed a commit with the extra `#include "arg.inl"` lines. LMK if there's anything else we should do here.

**Review by magnatelee — APPROVED** [review]

**Pull request merged**
