### PR TITLE
Add cuNumeric devcontainer

### PR DESCRIPTION
**Pull request by trxcllnt**
Opening this PR for visibility while I work on docs for what this all does.

### CODE REVIEW

**Comment by marcinz** [comment]
What are the unified and the isolated devcontainers in the conda directory for?

**Comment by trxcllnt** [comment]
@marcinz I am going to add a doc to this PR, but [here's a description](https://github.com/rapidsai/cuspatial/tree/branch-23.04/.devcontainer#via-launchsh) of the extra devcontainer flavors in cuSpatial.

**Comment by marcinz** [comment]
@trxcllnt Do you think this is ready to merge?

**Comment by trxcllnt** [comment]
@marcinz no, this is likely outdated. Jeremy and I are working on its replacement.

**Pull request closed without merging**
