### PR TITLE
Fix unit tests

### PR DESCRIPTION
**Pull request by magnatelee**

### CODE REVIEW

**Comment by magnatelee** [comment]
@bryevdv I just fixed unit tests, but I don't know why mypy isn't happy about the code. I can't locally reproduce the issue.

**Comment by bryevdv** [comment]
@magnatelee it looks like `mypy` skipped in the pre-commit job, not sure why. Did you see an actual error somewhere?

**Comment by magnatelee** [comment]
@bryevdv here's the mypy error I'm referring to: https://github.com/nv-legate/cunumeric/actions/runs/4890169367/jobs/8731114691 will see what this round of CI will say

**Comment by bryevdv** [comment]
👍 if it happens again I will try to match versions an repro locally

**Comment by bryevdv** [comment]
```
cunumeric/deferred.py:3087:14: error: Missing positional argument "pairs" in
call to "Annotation"  [call-arg]
```
@magnatelee there were two PRs for switching to context-less annotations/provenance (one for legate, one for cunumeric) This PR is seeing the legate change but not the cunumeric change (probably just need to merge latest)

**Comment by magnatelee** [comment]
@bryevdv it actually was on top of your PR, so I'm puzzled by the failure. I just pushed another commit, so hopefully it will pick up the right code this time. fyi, this is the history I'm seeing:

```
* 61981b74 - (70 seconds ago) Bump up the commit hash again - Wonchan Lee (HEAD -> commit-hash, origin/commit-hash)
* 8e88fdf1 - (7 hours ago) Fix unit tests - Wonchan Lee (nv-legate/pull-request/920)
*   97d1556c - (7 hours ago) Merge branch 'branch-23.05' into commit-hash - Wonchan Lee
|\  
| * 2e552efc - (8 hours ago) Update for Context-less annotations (#914) - Bryan Van de Ven (nv-legate/branch-23.05, nv-legate/HEAD, branch-23.05)
| * e71e52f3 - (19 hours ago) add negative test case test_searchedsorted.py (#916) - XiaLuNV
* | a55f95df - (20 hours ago) Bump up the commit hash - Wonchan Lee
```

**Comment by magnatelee** [comment]
@bryevdv looks like the mypy issue is still there: https://github.com/nv-legate/cunumeric/actions/runs/4898991083/jobs/8749693947?pr=920

**Comment by magnatelee** [comment]
@bryevdv I'm gonna just merge this PR, as without this the entire cuNumeric CI will stay broken; the separate CI for cuNumeric is finally working now and thus needs the right commit hash for legate core to be on your context-free provenance change. Let's address the mypy issue in a follow-on PR.

**Pull request merged**
