### PR TITLE
Uniform gen routines, std and var 

### PR DESCRIPTION
**Pull request by Saran-nns**
#126 Added random variate generator for uniform distribution `np.random.uniform`, `np.std` and `np.var`

### CODE REVIEW

**Comment by magnatelee** [comment]
@Saran-nns I believe you're still working on this PR, right? (thank you for taking a shot at this BTW!) Let me know if you got stuck in any way. I'd be happy to assist you. I could also take this over and finish the rest.

**Comment by Saran-nns** [comment]
Hi @magnatelee, yes, I am working on this PR here #126

**Comment by magnatelee** [comment]
So a Python implementation of an operator like this PR is always desirable whenever reasonable, but `random.uniform` isn't such an operator, and I think we should directly implement it using C++ kernels, just like how other random functions are implemented. Like I mentioned in #126, `np.vectorize` is very difficult to implement in the current setting and would go way beyond the scope of this PR. If you're interested in taking the C++ path I'm suggesting, I could guide you on how to write a C++ operator implementation. Otherwise, I can try to get this operator added soon. Let me know what you think.

**Comment by Saran-nns** [comment]
Yes, it would be great to get your guidance on adding the C++ operators for the RNGs in cuNumeric. I will proceed accordingly with this PR.

**Comment by magnatelee** [comment]
Doing some digging, it looks like we've already sort of had an implementation for the uniform random number generator, except that it's not hooked up with `random.uniform`; `random.rand` is already an implementation of uniform sampling but only for a fixed range of (0, 1). So what's really missing here is the entry point for `random.uniform` and making it pass a user defined range to the backend C++ tasks. You will need to update the following parts of the code (for which I think we should start a new PR and close this one):

* Define `uniform` in the `random` submodule, which you already did in this PR.
* Update `random_uniform` of `DeferredArray` and `EagerArray` to optionally take a low and high value (https://github.com/nv-legate/cunumeric/blob/branch-22.01/cunumeric/deferred.py#L1368-L1375)
* Pass `low` and `high` to `random`, just like `random_integer` passes its range to `random` (https://github.com/nv-legate/cunumeric/blob/branch-22.01/cunumeric/deferred.py#L1372, see how it's done in [`random_integer`](https://github.com/nv-legate/cunumeric/blob/branch-22.01/cunumeric/deferred.py#L1386-L1395))
* Finally, update the uniform RNG in C++ to handle the range correctly. (https://github.com/nv-legate/cunumeric/blob/branch-22.01/src/cunumeric/random/rand_util.h#L53-L66, see how it's done in the [integer RNG](https://github.com/nv-legate/cunumeric/blob/branch-22.01/src/cunumeric/random/rand_util.h#L176-L198).

Let me know if you have any questions. Like I said above, let's start a new PR for these changes.

**Comment by Saran-nns** [comment]
Thanks for the suggestions. I will create a new PR with the updates.

**Comment by Saran-nns** [comment]
Suggested updates were made at #137. Hence, I close this PR as a duplicate against it.

**Pull request closed without merging**
