### PR TITLE
v23.09.00

### PR DESCRIPTION
**Pull request by marcinz**
v23.09.00

### CODE REVIEW

**Comment by marcinz** [comment]
This must be merged with a merge commit.

**Comment by marcinz** [comment]
@sandeepd-nv The GPU build fails, but it also failed on the tip of `branch-23.09`. Do we treat this as a non issue?

**Comment by manopapad** [comment]
It doesn't seem possible to allow merge commits only on specific branches, so I just disabled the requirement for pull requests on the `main` branch. You should be able to just merge `branch-23.09` into `main` and push the update without going through a PR.

**Comment by marcinz** [comment]
I usually enable merge commits for a moment when I actually hit the button so that someone does not use it accidentally. :) The problem here is that the CI is not passing, but I think we can ignore this, right?

**Comment by manopapad** [comment]
> The problem here is that the CI is not passing, but I think we can ignore this, right?

Yeah, CI doesn't matter for this

**Pull request merged**
