### PR TITLE
WIP: Adding missing ufuncs

### PR DESCRIPTION
**Pull request by ipdemes**

### CODE REVIEW

**Comment by ipdemes** [comment]
@magnatelee or @manopapad : please review

**Review by manopapad — APPROVED** [review]
lgtm

**Comment by ipdemes** [comment]
@manopapad thanks ! I will add the rest of the ufuncs here before I remove WIP

**Comment by ipdemes** [comment]
I messed up git history in this branch so I created a new PR #134  and closing this one

**Pull request closed without merging**
