### PR TITLE
Mypy fix

### PR DESCRIPTION
**Pull request by magnatelee**
This PR fixes the outstanding mypy issues that some PRs are currently hitting. This also adds mypy to the pre-commit hooks.

### CODE REVIEW

**Review by bryevdv — APPROVED** [review]

**Comment by bryevdv** [comment]
This seems fine, still trying to repro locally

**Comment by bryevdv** [comment]
This is odd, `pre-commit run --all-files` is working fine for me locally on `branch-22.12` when did CI start failing?

**Comment by bryevdv** [comment]
Oh right, I don't think we can use `pre-commit` venv isolation, unless we can install `legate` into it. This works for me locally:
```
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.982'
      hooks:
        - id: mypy
          language: system
          pass_filenames: false
          args: ['cunumeric']
```
but assumes all the dev dependencies are installed.

**Comment by magnatelee** [comment]
> This is odd, mypy cunumeric is working fine for me locally on branch-22.12 when did CI start failing?

Here's one instance of failure: https://github.com/nv-legate/cunumeric/actions/runs/3426276253/jobs/5720273640 what version of mypy are you using?

**Comment by bryevdv** [comment]
0.982 the failing job uses 0.990. Unless we similarly pin the CI job I think we'd need to let them both float to latest

**Comment by magnatelee** [comment]
@bryevdv pre-commit.ci doesn't seem to have all the dependencies to run mypy correctly: https://results.pre-commit.ci/run/github/356975888/1668052514.pXdJum0_SpumCSjnj_zn-g I'll remove the hook for now and get this merged, and we will address this in a follow-on PR.

**Pull request merged**
