### PR TITLE
uniform generator routine #126

### PR DESCRIPTION
**Pull request by Saran-nns**
Following up with the [comment](https://github.com/nv-legate/cunumeric/pull/128#issuecomment-978161713) at PR #128

### CODE REVIEW

**Comment by magnatelee** [comment]
@Saran-nns See the build error: https://github.com/nv-legate/cunumeric/runs/4377342353?check_suite_focus=true#step:3:2650 Please make sure that your code actually compiles and passes the tests. (You can run the test suite by yourself using `test.py`.)

**Comment by magnatelee** [comment]
@Saran-nns any updates on this PR? I'd be happy to take over from here, if you don't have enough bandwidth.

**Comment by Saran-nns** [comment]
hi @magnatelee sorry for the delay. I added the missing parenthesis and ran the test suite. CPU tests passed only on *examples/benchmark.py*. To compare, I ran the test suite on the nv-legate:branch-22-22.01 and got the same results. 

Following that, 
I tried to install the CuNumeric from source using 
`python setup.py --with-core <path-to-legate-core-installation>` but it failed with exception as,

```cunumeric/mapper.cc: In constructor ‘cunumeric::CuNumericMapper::CuNumericMapper(Legion::Mapping::MapperRuntime*, Legion::Machine, const legate::LibraryContext&)’:
cunumeric/mapper.cc:31:66: error: no matching function for call to ‘legate::mapping::BaseMapper::BaseMapper(Legion::Mapping::MapperRuntime*&, Legion::Machine&, const legate::LibraryContext&)’
   31 |     eager_fraction(extract_env("CUNUMERIC_EAGER_FRACTION", 16, 1))
      |                                                                  ^
compilation terminated due to -Wfatal-errors.
make: *** [/home/saran/Documents/GitHub/legate.core/share/legate/legate.mk:200: cunumeric/mapper.cc.o] Error 1
make: *** Waiting for unfinished jobs....
/usr/local/cuda//bin/nvcc -o cunumeric/ternary/where.cu.o -c cunumeric/ternary/where.cu  -I/home/saran/Documents/GitHub/legate.core/install/thrust  -I. -Wno-deprecated-declarations -std=c++14 --expt-relaxed-constexpr --expt-extended-lambda -ccbin=g++ -I/home/saran/Documents/GitHub/legate.core/include -O2 -DPASCAL_ARCH -gencode arch=compute_60,code=sm_60 -DLEGATE_USE_CUDA -I/usr/local/cuda//include --compiler-options '-fPIC'
```

**on**

GTX 1060 Ti
CUDA version 11.5
Ubuntu 21.04

**Comment by magnatelee** [comment]
Looks like you haven't updated legate.core. Please pull and reinstall legate.core before you try to build cunumeric.

**Comment by magnatelee** [comment]
@Saran-nns I tried to build your branch myself and it looks outdated; once you merge it with the most recent branch-22.01, your build issue should be gone.

One more thing to note: to accept your PR, we need you to sign off every commit (https://github.com/nv-legate/cunumeric/blob/branch-22.01/CONTRIBUTING.md#how-do-i-sign-the-dco). You can do it simply by adding `-s` when you commit your changes. Unfortunately, the existing commits are not signed off, so you will need to amend and rebase them (here's one stackoverflow discussion about how to do it: https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits). Note that simply reverting the changes and recommitting them with sign-offs will not work, as the history will still contain the changes that aren't signed off.

**Comment by Saran-nns** [comment]
@magnatelee thanks for the feedback. I tried signing-off previous commits with rebase and received several conflicts. 

As a quick workaround, I created a new branch from the upstream/branch22.01 https://github.com/Saran-nns/cunumeric/tree/uniform_generator_routine and merged all my changes into a single commit there.

I created a new PR #176 and close this PR against it.

**Pull request closed without merging**
