### PR TITLE
Adding contributions file

### PR DESCRIPTION
**Pull request by marcinz**
Added contribution rules.

### CODE REVIEW

**Comment by magnatelee** [comment]
> I was thinking of adding code formatting request, but I thought that at the end it did not really matter much and it could unnecessarily make contributing more troublesome.
I disagree. We should keep the formatting consistent no matter who produced the code, as once an ill-formatted file gets merged, we have a chance to reformat it only when one of us changes it (assuming that we're using the pre-commit hooks). What we should avoid is requiring formatting and providing no instructions or tools. We've already had pre-commit hooks that enforce the formatting, so we simply need to ask the contributors to use them. Also, we really should set up style checks in our CI to block ill-formatted PRs from getting merged.

**Comment by mmccarty** [comment]
> We've already had pre-commit hooks that enforce the formatting, so we simply need to ask the contributors to use them. Also, we really should set up style checks in our CI to block ill-formatted PRs from getting merged.

+1  I also recommend adding instructions on how to install the pre-commit hooks.

**Comment by manopapad** [comment]
> set up style checks in our CI to block ill-formatted PRs from getting merged.

@marcinz how easy is it to do this? I assume an easy solution would be to run the pre-commit scripts during image build, and fail the build if the scripts fail. Would we then want to single-out the files touched by any commit in the RP, or just run on the entire repo?

**Comment by marcinz** [comment]
@manopapad It seems that pre-commit has a CI solution (http://pre-commit.ci). I enabled it for cunumeric. Let's see how it works out.

**Comment by manopapad** [comment]
@marcinz Looks like it works! https://github.com/nv-legate/cunumeric/pull/150/commits/1783d65a50e6613f18da1a199d1927a323cf3663

I think we're good to merge this PR

**Pull request merged**
