### PR TITLE
[WIP] Collate test output to allow workers > 1 with verbose output

### PR DESCRIPTION
**Pull request by bryevdv**
Still WIP but I want to see how CI performs.

### CODE REVIEW

**Comment by bryevdv** [comment]
@magnatelee This generally seems better (or at least comparable) to old CI runs in most cases. The exception is the GPU tests, which still seem to be slower. The CI machines have 2 GPUs and the new algo still only decides to use 1 worker for both tests. It seems like that's incorrect?

**Comment by bryevdv** [comment]
Edit, well this was incorrect:

> since they also had only 1 worker

The old tests use 2 workers:
```
### Entering stage: GPU (with 2 workers)
```
@magnatelee should we adjust the worker spec computation in the GPU stage?

**Comment by bryevdv** [comment]
The previous workers computation was more or less the current one, except without the bloat factor. Reducing it from 1.5 to 1.25 just to see how CI performs. @magnatelee should we make the bloat factor confugurable?

**Comment by magnatelee** [comment]
Ok. I think some clarification would help here. First of all, the `legate` launcher sets the framebuffer size to 4GB by default. Second, the 6GB budget in the test script already takes the bloating factor into account. That means `DEFAULT_GPU_MEMORY_BUDGET` used in the current test script is not the framebuffer size the launcher uses but the bloated one. I think two changes are needed:

1) Change `DEFAULT_GPU_MEMORY_BUDGET` to 4GB
2) Pass `config.fbmem` to to the launcher when running GPU tests (i.e., add `["--fbmem", config.fbmem]` to the launcher args for GPU tests)

Then, you can keep the bloating factor 1.5 and everything works as it did before. I'm fine with making the bloating factor configurable as well, but I don't expect developers to configure it by themselves.

**Comment by bryevdv** [comment]
@magnatelee I have made suggestion 1) in https://github.com/nv-legate/cunumeric/pull/507/commits/6aa51889af0f6e561adf3afc6232c45f154634dc 

When I try to add suggestion 2) get program aborts on my local system:
```
   
+LEGATE_TEST=1 /home/bryan/work/legate.core/install38/bin/legate /home/bryan/work/cunumeric/examples/cholesky.py -cunumeric:test --gpus 2 --gpu-bind 0,1 --fbmem 4294967296
[FAIL] (GPU) examples/cholesky.py
   /home/bryan/work/legate.core/install38/bin/bind.sh: line 107: 82933 Aborted                 numactl "$@"

```

**Comment by bryevdv** [comment]
Assuming the latest run is as good as the previous one:

image

I'd suggest merging this as-is, so that the team can benefit from faster CI jobs, and then making a follow-on issue about explicitly providing `--fbmem`

**Comment by magnatelee** [comment]
I think this part is problematic: `--fbmem 4294967296`. `--fbmem` takes a size in megabytes, so your command is asking for a 4PB space on framebuffer.

**Comment by bryevdv** [comment]
>  asking for a 4PB space on framebuffer.

https://github.com/nv-legate/cunumeric/pull/507/commits/3af2be815d942bc04f7545b01f6b0cc1f72e0c21 seems to fix locally :D

**Review by magnatelee — APPROVED** [review]

**Pull request merged**
