### PR TITLE
Move build instructions to sphinx docs

### PR DESCRIPTION
**Pull request by bryevdv**
cc @manopapad

### CODE REVIEW

**Review by manopapad — APPROVED** [review]

**Comment by bryevdv** [comment]
@manopapad let's wait until just before the release to merge this, since otherwise there won't be any easily accessible build instructions in the interim (cc @marcinz)

**Comment by marcinz** [comment]
Who was generating the docs until now? I guess we should have a CI job to generate the docs on release?

**Comment by bryevdv** [comment]
> Who was generating the docs until now? 

I actually have no idea, I assumed it was you :D 

> I guess we should have a CI job to generate the docs on release?

👍 for automating this if possible

**Comment by magnatelee** [comment]
> Who was generating the docs until now?

@ipdemes and I have been manually deploying the doc. You can check [gh-pages](https://github.com/nv-legate/cunumeric/tree/gh-pages) for the past deployments.

>  I guess we should have a CI job to generate the docs on release?

Looks like you're finally on board with the idea. :) Just to remind you briefly, we opened a JIRA task for automating the doc deployment about a year ago (which I though then would only take a couple of releases to roll out) and I believe it's already been assigned to you.

**Comment by ipdemes** [comment]
Actually the task was assigned to me fr some reason https://jirasw.nvidia.com/browse/CNM-114 .  I thought it was done with the latest release and closed it. Probably because documentation build was added to the CI (but apparently not the deployment) 
Here are the steps I follow to create docs for the new release https://gitlab-master.nvidia.com/groups/legate/-/wikis/Updating-cuNumeric-documentation-for-new-release

**Comment by magnatelee** [comment]
@ipdemes it looks like there are two JIRA tasks; maybe I didn't notice the existing one when I opened mine. the automatic doc generation/deployment is by no means done.

**Comment by bryevdv** [comment]
@manopapad I'll be out all next week, should we go ahead and merge? (or else someone else will need to remember to before release freeze)

**Comment by manopapad** [comment]
Yes, let's merge. I assume we still need to build and upload the docs manually after code freeze?

**Comment by bryevdv** [comment]
> I assume we still need to build and upload the docs manually after code freeze?

AFAIK that has not been automated

**Pull request merged**
